import "@app/styles/global.scss";
import { auth } from "@app/lib/auth";
import { SessionProvider } from "next-auth/react";
import type { Metadata } from "next";
import { Navbar } from "@app/components/navbar/navbar";
import { Providers } from "@app/components/providers/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://rsms.me/" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head>
      <SessionProvider session={session}>
        <body>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </body>
      </SessionProvider>
    </html>
  );
}
